openapi: 3.0.0
info:
  description: API for managing event locations
  title: Event Management Service
  version: 1.0.0
servers:
- url: http://localhost:8080
security:
- bearerAuth: []
tags:
- name: Locations
- name: Events
- name: Users
paths:
  /locations:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EventLocation'
                type: array
          description: Список всех локаций
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "List all event locations. roles=[user,admin]"
      tags:
      - Locations
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventLocation'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLocation'
          description: Место успешно создано
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "Создать новое место. roles=[admin]"
      tags:
      - Locations
  /locations/{locationId}:
    delete:
      parameters:
      - description: Уникальный идентификатор местоположения
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLocation'
          description: Место успешно удалено
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "404":
          content:
            application/json:
              example:
                message: Пользователь не найден
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Сущность не найдена
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "Удалить место. roles=[admin]"
      tags:
      - Locations
    get:
      parameters:
      - description: Уникальный идентификатор местоположения
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLocation'
          description: Успешный ответ
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "404":
          content:
            application/json:
              example:
                message: Пользователь не найден
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Сущность не найдена
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "Получить место по ID. roles=[user,admin]"
      tags:
      - Locations
    put:
      parameters:
      - description: Уникальный идентификатор местоположения
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventLocation'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventLocation'
          description: Место успешно обновлено
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "404":
          content:
            application/json:
              example:
                message: Пользователь не найден
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Сущность не найдена
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "Обновить место. roles=[admin]"
      tags:
      - Locations
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Пользователь успешно зарегистрирован
        "400":
          content:
            application/json:
              example:
                message: "Логин занят, попробуйте другой"
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: "запрос с ошибкой. Например, попытка занять занятый логин"
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      security: []
      summary: Регистрация нового пользователя
      tags:
      - Users
  /users/{userId}:
    get:
      parameters:
      - description: Уникальный идентификатор пользователя
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Информация о пользователе
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "403":
          content:
            application/json:
              example:
                message: Недостаточно прав
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: У пользователя недостаточно прав для выполнения этой операции
        "404":
          content:
            application/json:
              example:
                message: Пользователь не найден
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Сущность не найдена
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      summary: "Получить информацию о пользователе по ID. roles=[admin]"
      tags:
      - Users
  /users/auth:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
          description: "Авторизация успешна, возвращен JWT"
        "401":
          content:
            application/json:
              example:
                message: Необходима аутентификация
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Аутентификация отсутствует или не удалась
        "500":
          content:
            application/json:
              example:
                message: Внутренняя ошибка сервера
              schema:
                $ref: '#/components/schemas/MessageResponse'
          description: Внутренняя ошибка сервера
      security: []
      summary: Авторизация пользователя и получение JWT
      tags:
      - Users
components:
  parameters:
    locationId:
      description: Уникальный идентификатор местоположения
      in: path
      name: id
      required: true
      schema:
        format: int64
        type: integer
    userId:
      description: Уникальный идентификатор пользователя
      in: path
      name: id
      required: true
      schema:
        format: int64
        type: integer
  responses:
    Unauthorized:
      content:
        application/json:
          example:
            message: Необходима аутентификация
          schema:
            $ref: '#/components/schemas/MessageResponse'
      description: Аутентификация отсутствует или не удалась
    Forbidden:
      content:
        application/json:
          example:
            message: Недостаточно прав
          schema:
            $ref: '#/components/schemas/MessageResponse'
      description: У пользователя недостаточно прав для выполнения этой операции
    ServerError:
      content:
        application/json:
          example:
            message: Внутренняя ошибка сервера
          schema:
            $ref: '#/components/schemas/MessageResponse'
      description: Внутренняя ошибка сервера
    BadRequest:
      content:
        application/json:
          example:
            message: "Логин занят, попробуйте другой"
          schema:
            $ref: '#/components/schemas/MessageResponse'
      description: "запрос с ошибкой. Например, попытка занять занятый логин"
    NotFound:
      content:
        application/json:
          example:
            message: Пользователь не найден
          schema:
            $ref: '#/components/schemas/MessageResponse'
      description: Сущность не найдена
  schemas:
    MessageResponse:
      properties:
        message:
          type: string
      required:
      - message
      type: object
    EventLocation:
      example:
        address: "г. СПб, Пятилеток 1"
        name: Ледовый дворец
        description: Спортивно-концертный комплекс в Санкт-Петербурге
        id: 42
        capacity: 12300
      properties:
        id:
          example: 42
          format: int64
          readOnly: true
          type: integer
        name:
          example: Ледовый дворец
          type: string
        address:
          example: "г. СПб, Пятилеток 1"
          type: string
        capacity:
          example: 12300
          format: int32
          type: integer
        description:
          example: Спортивно-концертный комплекс в Санкт-Петербурге
          type: string
      required:
      - address
      - capacity
      - name
      type: object
    User:
      example:
        role: user
        id: 1
        login: user_login
        age: 21
      properties:
        id:
          example: 1
          format: int64
          readOnly: true
          type: integer
        login:
          example: user_login
          type: string
        age:
          example: 21
          type: int
        role:
          enum:
          - user
          - admin
          example: user
          type: string
      type: object
    UserRegistration:
      example:
        password: strongpassword
        login: new_user
        age: 21
      properties:
        login:
          example: new_user
          type: string
        password:
          example: strongpassword
          format: password
          type: string
        age:
          example: 21
          type: int
      required:
      - age
      - login
      - password
      type: object
    JwtResponse:
      example:
        jwtToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      properties:
        jwtToken:
          description: JWT token for authenticated user
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
      type: object
    UserCredentials:
      example:
        password: userpassword
        login: user_login
      properties:
        login:
          example: user_login
          type: string
        password:
          example: userpassword
          format: password
          type: string
      required:
      - login
      - password
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
